### ISSUE TITLE
web插件名问题

### ISSUE THREAD

**Issue by Gabrielxzx** [godros/luci-app-godproxy#2]
如题，使用godproxy在插件服务界面显示GodProxy滤广告，应该是漏了一个“过”字，虽然不影响使用，但是强迫症很困扰
![屏幕截图 2021-01-30 105439](https://user-images.githubusercontent.com/27126997/106345452-3753af80-62eb-11eb-86ff-e93c7e51cce5.png)

**Comment by godros** [comment]
特意少写了过字呢。滤广告   简单省事。

**Comment by Gabrielxzx** [comment]
> 特意少写了过字呢。滤广告 简单省事。

OK
